Repository littensy/slither, pull requests merged in 2023-10, with the labels that each got.

#148 Update README.md
  README.md
Labels: type:docs

#153 fix: sync camera with subject
  src/client/components/world/snakes/snake-head.tsx
  src/client/components/world/snakes/snake.tsx
  src/client/components/world/snakes/snakes.tsx
  src/client/components/world/snakes/use-snake-bindings.ts
Labels: type:bug, game:app

#154 perf(voice): update characters less frequently
  src/client/components/voice/voice-character.tsx
  src/client/components/voice/voice.tsx
Labels: game:app, type:perf

#155 chore: housekeeping
  aftman.toml
  src/client/alerts/alerts.client.ts
  src/client/alerts/handlers/alert-remote.ts
  src/client/components/alerts/alert.tsx
  src/client/components/error-handler/error-page.tsx
  src/client/components/menu/home/home-footer.tsx
  src/client/components/menu/home/home-version.tsx
  src/client/components/menu/home/mute-button.tsx
  src/client/components/menu/home/play-button.tsx
  src/client/components/menu/home/spectate-button.tsx
  src/client/components/menu/menu-container.tsx
  src/client/components/menu/menu-vignette.tsx
  src/client/components/menu/navigation/destination.tsx
  src/client/components/menu/skins/act-button.tsx
  src/client/components/menu/skins/skin-indicator.tsx
  src/client/components/menu/support/support-footer.tsx
  src/client/components/menu/support/support-heart.tsx
  src/client/components/menu/support/support-premium.tsx
  src/client/components/menu/support/support-product.tsx
  src/client/components/stats/stats-card.tsx
  src/client/components/ui/delay-render.tsx
  src/client/components/ui/input-capture.tsx
  src/client/components/ui/primary-button.tsx
  src/client/components/ui/reactive-button/use-button-animation.ts
  src/client/components/ui/render-in-view.tsx
  src/client/components/ui/text-field.tsx
  src/client/components/ui/text.tsx
  src/client/components/world/backdrop/backdrop-ball.tsx
  src/client/components/world/candy/candy-item.tsx
  src/client/components/world/candy/candy.tsx
  src/client/components/world/snakes/snake-head.tsx
  src/client/components/world/snakes/snake-name-tag.tsx
  src/client/components/world/snakes/snakes.tsx
  src/client/components/world/snakes/use-snake-bindings.ts
  src/client/components/world/world-border.tsx
  src/client/constants/fonts.ts
  src/client/constants/springs.ts
  src/client/reset/index.client.ts
  src/server/rewards/utils.ts
Labels: type:refactor

#156 fix: third place badge
  src/server/rewards/services/badges.ts
Labels: type:bug, game:server

#157 style: remove unused vars
  .eslintrc
  src/client/components/menu/menu.tsx
  src/server/bots/bot-behavior.ts
  src/shared/test/utils/grid.bench.ts
Labels: type:refactor

#163 fix: check players already in game
  src/server/players/services/character.ts
  src/server/players/services/save.ts
  src/server/players/services/scoreboard.ts
  src/shared/utils/player-utils.ts
Labels: type:bug, game:server
